config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do 
    resource :profile
    resources :messages
  end
  
  resources :freelancers do
    resource :ability
  end
  
  resources :teams
  resources :matches
  resources :admin
  resources :events
  
  get 'about', to: 'pages#about'
  get 'ppl', to: 'pages#leaguesignup'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/event.rb
class Event < ApplicationRecord
    has_and_belongs_to_many :teams 
    has_many :matches
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    
    
    def index
      is_captain
      @events = Event.all
      @event = Event.new
    end
    
    def show
      is_captain
      @event = Event.find(params[:id])
      @teams = @event.teams
      @match_list = Array.new()
      @match_list << Match.where("event_id == ?", @event.id).where("round == 1")
      @match_list << Match.where("event_id == ?", @event.id).where("round == 2")
      @match_list << Match.where("event_id == ?", @event.id).where("round == 3")
      @match_list << Match.where("event_id == ?", @event.id).where("round == 4")
      @match_list << Match.where("event_id == ?", @event.id).where("round == 5")
      @match = Match.new()
    end
    
    def update
      # Get the event & list of event teams
      @event = Event.find(params[:id])
      @event_teams = @event.teams
      
      # If the user is trying to remove a team from the league
      if params[:event][:msg] == "leave"
        # Check if the team is already part of the event
        @new_team = Team.find(params[:event][:team_id])
        if @event_teams.include?@new_team
          
          # Remove the team and output a message to the user
          @event.teams.delete(@new_team)
          flash[:danger] = @new_team.name + " has left " + @event.name
        end
        
      # If a team is trying to join the league
      elsif params[:event][:msg] == "join"
        # Check if the team is already part of the event
        # Flash an error message notifying the user that they have already joined
        @new_team = Team.find(params[:event][:team_id])
        if @event_teams.include?@new_team
          flash[:danger] = "Your team is already signed up for " + @event.name + "!"
        # Otherwise, add the team to the event and flash a confirmation message
        else
          @event.teams << @new_team
          flash[:success] = "Your team has signed up for " + @event.name + "!"
        end
        
      # Toggle the event status between open/close
      elsif params[:event][:msg] == "close"
        if @event.status == "open"
          @event.status = "closed"
        else
          @event.status = "open"
        end
        @event.save
      end
      
      # Return to event page
      redirect_to event_path( @event.id )
    end
    
    private
      # Function to confirm if the user is the captain of a team
      def is_captain
        @captain = false
        # Check if the user is signed in and has a profile
        if user_signed_in?
          if current_user.profile 
            # Check if the user is part of a team and find the team
            if current_user.profile.team_id > 0
              team = Team.find(current_user.profile.team_id)
              # If the user is the captain of the team, check that they have 
              # the required amount of players on the team and set captain to true
              if current_user.id == team.user_id
                if team.profiles.count >= 4
                  @captain = true
                end
              end
            end
          end
        end
      end
end

app/views/events/_form.html.erb
<%= form_for @match, url: matches_path, :html => { :multipart => true } do |f| %>
    <%= hidden_field(:type, "submit") %>
    <%= f.hidden_field(:event_id, :value => @event.id) %>
    <%  
    select_fields = Array.new()
    @event.teams.each do |team|
        select_fields << [team.name, team.id]
    end
    %>
    <div class = 'form-group'>
        <%= f.label :round %>
        <%= f.number_field :round, class: 'form-control' %>
    </div>
    
    <div class = 'form-group'>
        <%= f.label :home_team %>
        <%= f.select :home_team, select_fields, {}, class: 'form-control' %>
    </div>
    
    <div class = 'form-group'>
        <%= f.label :away_team %>
        <%= f.select :away_team, select_fields, {}, class: 'form-control' %>
    </div>
    
    <div class = 'form-group'>
        <%= f.submit "Create Match", class: "btn btn-primary" %>
    </div>
    
<% end %>

app/views/events/index.html.erb
<div class = "container">
  <div class = "row">
    <h1>Prep Phase Events</h1>
    <div class = "col-md-6">
      <h3>Open Events</h3>
      <ul class = "list-unstyled">
        <% @events.where(:status => "open").each do |e| %>
        <li>
          <div class = "row well well-index <%= cycle('', 'light-bg') %>" %>
            <%= link_to root_path do %>
            <div class = "col-sm-8 ">
                <span class = "index-user-desc"><%= e.name %></span>
                <h5><i>(<%= e.date %> <%= e.time %>) </i>&emsp;
                  <span class = "label index-label">
                    <%= e.event_type %>
                  </span>
                </h5>
            </div>
            <% end %>
            <% if @captain %>
            <div class = "col-sm-4">
              <%= form_for e, url: event_path(id: e.id), :html => { :multipart => true } do |f| %>
                <%= f.hidden_field :team_id, :value => current_user.profile.team_id %>
                <%= f.hidden_field :msg, :value => "join" %>
                <%= submit_tag( "Sign Up", class: "btn btn-info" ) %>
              <% end %>
            </div>
            <% end %>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
    <div class = "col-md-5 col-md-offset-1">
      <h3>Recent Events</h3>
      <ul class = "list-unstyled">
      <% @events.where(:status => "closed").each do |e| %>
        <li>
          <div class = "row well well-index <%= cycle('', 'light-bg') %>" %>
            <%= link_to root_path do %>
            <div class = "col-sm-8 ">
                <span class = "index-user-desc"><%= e.name %></span>
                <h5><i>(<%= e.date %> <%= e.time %>) </i>&emsp;
                  <span class = "label index-label">
                    <%= e.event_type %>
                  </span>
                </h5>
            </div>
            <% end %>
          </div>
        </li>
        <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class = 'container'>
  <div class = 'row well'>
    <h1><%= @event.name %></h1>
    <div class = "col-md-3">
      <h3>Event Details</h3>
      <p>
        <%= @event.event_type %> Event<br/>
        Status: <%= @event.status.capitalize %><br/>
        Date: <%= @event.date %><br/>
        Time: <%= @event.time %><br/>
        Matches: <%= @event.num_matches %>
      </p>
      <% if user_signed_in? %>
        <!-- If user owns the team they can remove them from the event -->
        <% if @event.status == "open" and @captain %>
          <%= form_for @event, url: event_path(id: @event.id), :html => { :multipart => true } do |f| %>
            <%= f.hidden_field :team_id, :value => current_user.profile.team_id %>
            <%= f.hidden_field :msg, :value => "join" %>
            <%= submit_tag( "Sign Up", class: "btn btn-info text-center" ) %>
          <% end %>
        <% end %>
        <% if current_user.user_type == "admin" %>
          <%= form_for @event, url: event_path(id: @event.id), :html => { :multipart => true } do |f| %>
            <%= f.hidden_field :msg, :value => "close" %>
            <%= submit_tag( "Toggle Event", class: "btn btn-warning text-center" ) %>
          <% end %>
          <br/>
          <button type="button" class="btn btn-info" data-toggle="modal" data-target="#match_modal">Create Match</button>
        <% end %>
      <% end %>
    </div>
    <div class = "col-md-9">
      <h3>Teams</h3>
      <% @teams.each do |t| %>
        
        <div class = "row">
          <div class = "col-md-6">
            <%= link_to team_path(id: t.id) do %>
            <%= image_tag t.avatar.url, class: 'user-index-avatar'%>
            &emsp;<%= t.name %>
            <% end %>
          </div>
          <div class = "col-md-4">
            
          </div>
          
          <div class = "col-md-4">
            <% if @event.status == "open" %>
              <% if user_signed_in? %>
               <!-- If user owns the team they can remove them from the event -->
                <% if (t.user_id == current_user.id) || (current_user.user_type == "admin") %>
                  <%= form_for @event, url: event_path(id: @event.id), :html => { :multipart => true } do |f| %>
                    <%= f.hidden_field :msg, :value => "leave" %>
                    <%= f.hidden_field :team_id, :value => t.id %>
                    <%= submit_tag( "Remove Team", class: "btn btn-danger" ) %>
                  <% end %>
                <!-- Admins can remove teams from events -->
                <% end %>
              <% end %>
            <% else %>
              Wins: 0<br/>
              Losses: 0<br/>
              Points: 0
            <% end %>
          </div>
          
        </div>
        <br/><br/>
      <% end %>
    </div>
  </div> <!-- /top row well -->
    <div class = 'row well text-center'>
      <h2>Matches</h2>
      <% @match_list.each_with_index do |round, i| %>
        <% if round[0] %>
        <div class = "col-md-4">
          <h3>Round <%= i + 1 %></h3>
          <% round.each do |m| %>
            <div class = "col-sm-5">
              <%= @teams.find{|t| t.id == m.home_team}.name %>
            </div>
            <div class = "col-sm-2">V</div>
            <div class = "col-sm-5">
              <%= @teams.find{|t| t.id == m.away_team}.name %>
            </div>
          </br>
          <% end %>
        </div>
        <% end %>
      <% end %>
    </div> <!-- /matches row well -->
</div>

<div id="match_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create Match</h4>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>