config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do 
    resource :profile
    resources :messages
  end
  
  resources :freelancers do
    resource :ability
  end
  
  resources :teams
  resources :matches
  resources :admin
  resources :events
  
  get 'about', to: 'pages#about'
  get 'ppl', to: 'pages#leaguesignup'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/views/pages/about.html.erb
<div class="container text-center">
    <h1>About Page</h1>
    <p>We are DevMatch. Our company focuses on creating an exclusive community for 
    investors, developers and entrepreneurs to meet each other.</p>
</div>

app/views/pages/home.html.erb
<!--<div class="container-fluid text-center home-callout">
    <h1>Welcome to Prep Phase</h1>
    <h3>The home page for all your Atlas Reactor needs!</h3>
</div> -->
<div class="container home-sign-up-links">
    <div class="row">
            <div class="col-md-8">
                <div class="well well-home row">
                    <h3 class="text-center">Freelancers</h3>
                    <div class = "text-center">
                    <% @freelancers.each do |char| %>
                        <%= link_to freelancer_path(id: char.id) do %>
                            <div class = "freelancer-img"><%= image_tag char.image_url, class: "grn-border" %></div>
                        <% end %>
                    <% end %>
                    </div>
                </div>
                <div class = "row well carousel-well">
                    <div id="carousel-event" class="col-md-12 carousel slide" data-ride="carousel">
                      <!-- Wrapper for slides -->
                      <div class="carousel-inner" role="listbox">
                        <% @events.each do |e| %>
                        <div class="item active">
                          <%= link_to event_path(e.id) do %>
                          <h2><%= e.name %></h2>
                          <span><%= e.date %>&emsp;<%= e.time %></span>
                          <% end %>
                        </div>
                        <% end %>
                        <div class="item">
                          <h2>More Events Coming Soon!</h2>
                        </div>
                      </div>
                    
                      <!-- Controls -->
                      <a class="left carousel-control" href="#carousel-event" role="button" data-slide="prev">
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="right carousel-control" href="#carousel-event" role="button" data-slide="next">
                        <span class="sr-only">Next</span>
                      </a>
                    </div>
                </div>
                <div class = "row">
                    <div class = "col-md-6 league-col well">
                        <h3>New Teams</h3>
                        <% @teams.each do |t| %>
                            <h4><%= t.name %></h4>
                        <% end %>
                    </div>
                    <div class = "col-md-6 league-col well">
                        <h3>Free Agents</h3>
                        <% @users.each do |u| %>
                            <%= link_to user_path(id: u.user_id) do %>
                                <% if !u.avatar %>
                                    <%= image_tag u.avatar.url, class: 'user-home-avatar' %>
                                <% elsif %>
                                    <i class="fa fa-superpowers"></i>
                                <% end %>
                            <% end %>
                          <%= u.username %>&emsp;
                          <span class = "label label-<%= u.favorite_role.downcase %>">
                            <%= u.favorite_role %>
                          </span>
                        <% end %>
                    </div>
                </div>
                <!-- Guides to be implemented
                <div class="well well-home row">
                    <h2 class="text-center">Top Guides</h2>
                    </% 6.times do |x| %>
                        <div class = "col-md-4 grn-border home-guide-box">
                            <div class = "col-sm-4">
                                <div class = "freelancer-img grn-border"></div>
                            </div>
                            <div class = "col-sm-8">
                                <div class = "home-guide-text">
                                    <h4>Guide </%= x + 1 %></h4>
                                    <span>By User</span>
                                </div>
                            </div>
                        </div>
                    </% end %>
                </div> 
                -->
            </div>
            <div class="col-md-4">
                <div class="well well-home">
                    <% if user_signed_in? %>
                        <% if current_user.profile %>
                            <h2 class="text-center">Get Involved</h2>
                            <%= link_to "Create a Guide", new_team_path, class: 'btn btn-block btn-info' %>
                            <%= link_to "Join the PPL", ppl_path, class: 'btn btn-block btn-success' %>
                        <% else %>
                            <h2 class = "text-center">Your Profile</h2>
                            <p>Create your profile to start taking part in the community!</p>
                            <%= link_to "Create Your Profile!", new_user_profile_path(user_id: current_user.id), class: 'btn btn-primary btn-lg btn-block' %>
                        <% end %>
                    <% else %>
                        <h2 class="text-center">Sign Up</h2>
                        <h4>Sign up now to become a member of the Prep Phase community,
                        allowing you to create guides, join the Prep Phase League and more!</h4>
                        <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-lg btn-block" %>
                    <% end %>
                </div>
                <div class = "well well-home">
                    <h2>PPL Leaderboard</h2>
                    <h3 class = "text-center">Coming Soon</h3>
                    <!--<ul>
                        </% 8.times do |x| %>
                            <li class = "lb-team row">
                                <div class = "col-sm-2">
                                    <span class = "freelancer-img grn-border"></span>
                                </div>
                                <div class = "col-sm-7 col-sm-offset-1">
                                    <h4>Team </%= x + 1 %></h4>
                                </div>
                            </li>
                        </% end %>
                    </ul>-->
                </div>
            </div>
            
    </div>
</div>

app/views/pages/leaguesignup.html.erb
<div class = "container">
    <div class = "row">
        <div class = "col-md-6 col-md-offset-3 well">
            <h1 class = "text-center">Welcome to the PPL!</h1>
            <p>
                The Prep Phase League(PPL) is an ongoing competitive environment
                for Atlas Reactor. In the PPL, teams compete over the course of 
                6 weeks by choosing to enter in to weekly events to earn points.
                There will be two weekly events, one at 17:00PST on Saturday, 
                the other at 18:00BST on Sunday to accommodate different 
                time-zones. Teams can sign up to one event per week and events 
                will consist of 2 matches, each match being a best of 2 series.
                <br/><br/>
                In order to compete in the PPL, each player must sign up 
                individually and then form a team of at least 4 members. The 
                team captain who created the team will then be allowed to sign 
                up to one of the two available weekly events. Rules regarding 
                the league can be found on the rules page
                <br/><br/>
                By joining the league you agree to the rules and regulations set
                out by the PPL staff. These rules can be found here
            </p>
            <br/>
            <% if user_signed_in? %>
                <% if current_user.profile.glyphtag %>
                    <% if current_user.profile.freeagent == false %>
                        <%= form_for current_user.profile, url: user_profile_path(user_id: current_user.id) do |f| %>
                            <%= f.submit "Sign up to play!", class: "btn btn-block btn-warning" %>
                        <% end %>
                    <% else %>
                        <%= link_to "Create A Team!", new_team_path, class: 'btn btn-block btn-info' %>
                    <% end %>
                <% else %>
                    <p>Add a glyphtag to your profile to sign up to the PPL!</p>
                    <%= link_to "Update Your Profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-block btn-info' %>
                <% end %>
            <% else %>
                <p>You must sign up to Prep Phase before joining the league</p>
                <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-block btn-info' %>
            <% end %>
        
        </div>
    </div>
</div>