config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do 
    resource :profile
    resources :messages
  end
  
  resources :freelancers do
    resource :ability
  end
  
  resources :teams
  resources :matches
  resources :admin
  resources :events
  
  get 'about', to: 'pages#about'
  get 'ppl', to: 'pages#leaguesignup'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prep Phase</title>
    <%= csrf_meta_tags %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="pulse"></div>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do%>
          <i class="fa fa-exchange"></i> Prep Phase
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
        <ul class="nav navbar-nav navbar-default">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  Freelancers <span class = "fa fa-angle-double-down"></span>
                </a>
              <ul class="dropdown-menu list-inline nav-freelancer">
                <% @freelancers.each do |freelancer| %>
                    <li><%= link_to freelancer.name, freelancer_path(id: freelancer.id) %></li>
                <% end %>
              </ul>
            </li>
            <!-- Guides Menu To Be Implemented
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                     Guides <span class = "fa fa-angle-double-down"></span>
                </a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> 
            -->
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    League <span class = "fa fa-angle-double-down"></span> 
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to 'Events', events_path %></li>
                    <!-- Team index to be added <li><%= link_to 'Teams', teams_path %></li> -->
                    <!-- Leaderboards to be implemented <li><a href="#">Leaderboards</a></li> -->
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Free Agents", users_path %></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Rules</a></li>
                </ul>
            </li>
        </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle profile-dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <% if current_user.profile %>
                        <%= current_user.profile.username %> 
                        <% if @num_msg > 0 %>
                            <span class = "label label-success"><%=@num_msg%></span>&emsp;
                        <% end %>
                        <% if current_user.profile.avatar %>
                            <%= image_tag current_user.profile.avatar, class: "grn-border" %>
                        <% end %>
                    <% else %>
                        user<%= (current_user.id * current_user.created_at.to_f).floor %>
                    <% end %>
                </a>
              <ul class="dropdown-menu">
                <% if current_user.profile %>
                    <li><%= link_to "Inbox", user_messages_path(user_id: current_user.id) %></li>
                    <% if current_user.profile.team_id %>
                        <li><%= link_to "Your Team", team_path(id: current_user.profile.team_id) %></li>
                    <% end %>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "View Profile", user_path(id: current_user.id) %></li>
                    <li><%= link_to "Edit Profile", edit_user_profile_path(user_id: current_user.id) %></li>
                    
                <% else %>
                    <li><%= link_to "Edit Profile", new_user_profile_path(user_id: current_user.id) %></li>
                <% end %>
                <li><%= link_to "My Account", edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger navbar-btn' %></li>
              </ul>
            </li>
            <% else %>
                <%= link_to "Login", new_user_session_path, class: 'btn btn-default navbar-btn' %>
            <% end %>
          </ul>
          <!-- <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>
          </ul>-->
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <div class = "container flash-container">
        <% flash.each do |type, msg| %>
            <%= content_tag :div, msg, class: "alert alert-#{type}" %>
        <% end %>
    </div>
    
    <%= yield %>
    
  </body>
</html>